-- UNUtrip v2 - Migration 009 (data migration)
-- Purpose: Populate `rag_knowledge_base` from legacy `rag_places` (first cut).
-- Safety:
-- - Inserts/updates v2 rows only.
-- - Does NOT drop or alter legacy tables.
-- - Designed to be re-runnable via ON DUPLICATE KEY UPDATE.
--
-- Locked decisions implemented:
-- - Primary source: rag_places (JSONL ingestion deferred).
-- - knowledge_key = CONCAT('rag_place:', rag_places.place_id)
-- - knowledge_type = 'place'
-- - app_place_id = rag_places.destination_id
-- - place_key = rag_places.place_id
-- - last_updated stays VARCHAR-compatible text
-- - quality_score is copied only into rag_knowledge_base.quality_score (never app rating)

INSERT INTO `rag_knowledge_base` (
  `knowledge_key`,
  `place_key`,
  `app_place_id`,
  `title`,
  `knowledge_type`,
  `content`,
  `summary`,
  `province`,
  `city`,
  `area`,
  `destination_group`,
  `address`,
  `latitude`,
  `longitude`,
  `aliases_json`,
  `category_main`,
  `category_sub`,
  `category_main_norm`,
  `category_sub_norm`,
  `tags_json`,
  `interest_tags_json`,
  `suitable_for_json`,
  `avoid_for_json`,
  `open_time`,
  `close_time`,
  `best_time_of_day_json`,
  `suggested_slot`,
  `slot_norm`,
  `duration_minutes`,
  `is_night_activity`,
  `is_free`,
  `entry_fee_min`,
  `entry_fee_max`,
  `budget_level`,
  `budget_level_norm`,
  `price_note`,
  `walking_level`,
  `walking_level_norm`,
  `activity_level`,
  `activity_level_norm`,
  `elderly_friendly`,
  `elderly_friendly_norm`,
  `kid_friendly`,
  `kid_friendly_norm`,
  `nearby_area_json`,
  `transport_suggestion_json`,
  `quality_score`,
  `recommended_use`,
  `recommended_use_norm`,
  `is_generic`,
  `must_not_schedule_as_main`,
  `requires_realtime_check`,
  `realtime_fields_json`,
  `source`,
  `source_url`,
  `last_updated`,
  `is_active`,
  `search_text`,
  `raw_json`,
  `created_at`,
  `updated_at`
)
SELECT
  CONCAT('rag_place:', rp.`place_id`) AS `knowledge_key`,
  rp.`place_id` AS `place_key`,
  rp.`destination_id` AS `app_place_id`,
  rp.`name` AS `title`,
  'place' AS `knowledge_type`,
  rp.`description` AS `content`,
  rp.`short_description` AS `summary`,
  rp.`province`,
  rp.`city`,
  rp.`area`,
  rp.`destination_group`,
  rp.`address`,
  rp.`latitude`,
  rp.`longitude`,
  rp.`aliases_json`,
  rp.`category_main`,
  rp.`category_sub`,
  rp.`category_main_norm`,
  rp.`category_sub_norm`,
  rp.`tags_json`,
  rp.`interest_tags_json`,
  rp.`suitable_for_json`,
  rp.`avoid_for_json`,
  rp.`open_time`,
  rp.`close_time`,
  rp.`best_time_of_day_json`,
  rp.`suggested_slot`,
  rp.`slot_norm`,
  rp.`duration_minutes`,
  rp.`is_night_activity`,
  rp.`is_free`,
  rp.`entry_fee_min`,
  rp.`entry_fee_max`,
  rp.`budget_level`,
  rp.`budget_level_norm`,
  rp.`price_note`,
  rp.`walking_level`,
  rp.`walking_level_norm`,
  rp.`activity_level`,
  rp.`activity_level_norm`,
  rp.`elderly_friendly`,
  rp.`elderly_friendly_norm`,
  rp.`kid_friendly`,
  rp.`kid_friendly_norm`,
  rp.`nearby_area_json`,
  rp.`transport_suggestion_json`,
  rp.`quality_score`,
  rp.`recommended_use`,
  rp.`recommended_use_norm`,
  rp.`is_generic`,
  rp.`must_not_schedule_as_main`,
  rp.`requires_realtime_check`,
  rp.`realtime_fields_json`,
  rp.`source`,
  rp.`source_url`,
  rp.`last_updated`,
  rp.`is_active`,
  rp.`search_text`,
  rp.`raw_json`,
  rp.`created_at`,
  rp.`updated_at`
FROM `rag_places` rp
ON DUPLICATE KEY UPDATE
  `place_key` = VALUES(`place_key`),
  `app_place_id` = VALUES(`app_place_id`),
  `title` = VALUES(`title`),
  `knowledge_type` = VALUES(`knowledge_type`),
  `content` = VALUES(`content`),
  `summary` = VALUES(`summary`),
  `province` = VALUES(`province`),
  `city` = VALUES(`city`),
  `area` = VALUES(`area`),
  `destination_group` = VALUES(`destination_group`),
  `address` = VALUES(`address`),
  `latitude` = VALUES(`latitude`),
  `longitude` = VALUES(`longitude`),
  `aliases_json` = VALUES(`aliases_json`),
  `category_main` = VALUES(`category_main`),
  `category_sub` = VALUES(`category_sub`),
  `category_main_norm` = VALUES(`category_main_norm`),
  `category_sub_norm` = VALUES(`category_sub_norm`),
  `tags_json` = VALUES(`tags_json`),
  `interest_tags_json` = VALUES(`interest_tags_json`),
  `suitable_for_json` = VALUES(`suitable_for_json`),
  `avoid_for_json` = VALUES(`avoid_for_json`),
  `open_time` = VALUES(`open_time`),
  `close_time` = VALUES(`close_time`),
  `best_time_of_day_json` = VALUES(`best_time_of_day_json`),
  `suggested_slot` = VALUES(`suggested_slot`),
  `slot_norm` = VALUES(`slot_norm`),
  `duration_minutes` = VALUES(`duration_minutes`),
  `is_night_activity` = VALUES(`is_night_activity`),
  `is_free` = VALUES(`is_free`),
  `entry_fee_min` = VALUES(`entry_fee_min`),
  `entry_fee_max` = VALUES(`entry_fee_max`),
  `budget_level` = VALUES(`budget_level`),
  `budget_level_norm` = VALUES(`budget_level_norm`),
  `price_note` = VALUES(`price_note`),
  `walking_level` = VALUES(`walking_level`),
  `walking_level_norm` = VALUES(`walking_level_norm`),
  `activity_level` = VALUES(`activity_level`),
  `activity_level_norm` = VALUES(`activity_level_norm`),
  `elderly_friendly` = VALUES(`elderly_friendly`),
  `elderly_friendly_norm` = VALUES(`elderly_friendly_norm`),
  `kid_friendly` = VALUES(`kid_friendly`),
  `kid_friendly_norm` = VALUES(`kid_friendly_norm`),
  `nearby_area_json` = VALUES(`nearby_area_json`),
  `transport_suggestion_json` = VALUES(`transport_suggestion_json`),
  `quality_score` = VALUES(`quality_score`),
  `recommended_use` = VALUES(`recommended_use`),
  `recommended_use_norm` = VALUES(`recommended_use_norm`),
  `is_generic` = VALUES(`is_generic`),
  `must_not_schedule_as_main` = VALUES(`must_not_schedule_as_main`),
  `requires_realtime_check` = VALUES(`requires_realtime_check`),
  `realtime_fields_json` = VALUES(`realtime_fields_json`),
  `source` = VALUES(`source`),
  `source_url` = VALUES(`source_url`),
  `last_updated` = VALUES(`last_updated`),
  `is_active` = VALUES(`is_active`),
  `search_text` = VALUES(`search_text`),
  `raw_json` = VALUES(`raw_json`),
  `created_at` = VALUES(`created_at`),
  `updated_at` = VALUES(`updated_at`);

